name: Run Python Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
      shell: bash

    - name: Add uv to PATH
      run: echo "$HOME/.uv/bin" >> $GITHUB_PATH
      shell: bash

    - name: Create Virtual Environment
      run: uv venv

    - name: Install dependencies with uv
      run: uv pip install -r requirements-dev.txt

    - name: Run tests
      run: uv run python -m unittest discover